title: KnexChain
email: hello@knexmail.com
description: Revolutionary quantum-resistant blockchain infrastructure

# CRITICAL: GitHub Pages settings
baseurl: "/knexcoin.com"
url: "https://lifehackcheater.github.io"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Project info
project:
  tagline: "Crypto Pioneers. Innovators. The people that make life easy."
  license: "MIT"

github_username: lifehackcheater
twitter_username: knexchain
